version: "3.9"
services:
  user-db:
    container_name: user-db
    image: postgres:16-alpine
    environment:
      POSTGRES_DATABASE: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
volumes:
  user-db-data: