spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/user_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        default_schema: users
  liquibase:
    change-log: classpath:db/changelog-master.yml
    enabled: true
    liquibase-schema: public

